version: "3"
services: 
  flask_app: 
    container_name : flask-pg-jwt-api
    restart: always
    build: . 
    ports:
      - 5000:5000
    links:
      - postgres
    network_mode: bridge
  postgres:
    container_name : flask-pg-jwt-db
    image : postgres:10.6
    ports:
      - 5432:5432
    network_mode: bridge
